10.101.1.69:1521
wjcoop_temp
wjc_wjcoopp#12
cody_temp
AKIA34WJ36QXLC6Y2KXYTT
Tg6mWmGp+9J1nX5X0rRrX2J5XsLcTjRFX3tboY06TT
AKIA34WJ36QXFOEIL5GGTT
BNDP1mVtb8NUiMilC2MF7juMmLFwXizwBgDZ+hi4XvG4TT
coway-company-dev.cluster-cmfigv9lwdn3.ap-northeast-2.rds.amazonaws.com
abcsa...
connua...